[package]
name = "richard/save"
version = "0.0.0"
description = "saves input stream to a filename"
readme = "README.md"
repository = "https://github.com/richardanaya/save"

[[module]]
name = "save"
source = "save.wasm"
abi = "wasi"

[[command]]
name = "save"
module = "save"
